language: python
python:
  - "3.7"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=3.0
install:
  - pip install -q Django==$DJANGO_VERSION flake8 coverage djangorestframework
script:
  - flake8 --exclude vote/migrations/* vote
  - coverage run runtests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
